hsvpy/hsvpy/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='base.html')),

    # Examples:
    # url(r'^$', 'hsvpy.views.home', name='home'),
    # url(r'^hsvpy/', include('hsvpy.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^stories/', include('stories.urls')),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

hsvpy/stories/urls.py
from django.conf.urls import patterns, include, url

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name="stories"),
    url(r'^story/(?P<story_id>[0-9]+)/$', views.show_story, name="show-story"),
    url(r'^add-story/$', views.add_story, name="add-story"),
    url(r'^edit-story/(?P<story_id>[0-9]+)/$', views.edit_story, name="edit-story"),
    url(r'^add-paragraph/(?P<story_id>[0-9]+)/$', views.edit_paragraph, name="add-paragraph"),
    url(r'^edit-paragraph/(?P<story_id>[0-9]+)/(?P<para_id>[0-9]+)/$', views.edit_paragraph,
        name="edit-paragraph"),
)

hsvpy/stories/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Story(models.Model):
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Stories"

    def __unicode__(self):
        return self.title

    def last10paragraphs(self):
        """ return the last 10 paragraphs of this story"""
        return Paragraph.objects.filter(story=self)[:10]


class Paragraph(models.Model):
    story = models.ForeignKey(Story)
    text = models.TextField()
    written_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at', )

    def __unicode__(self):
        return self.text

hsvpy/stories/forms.py
from django import forms

from .models import Paragraph, Story

class ParagraphForm(forms.ModelForm):
    class Meta:
        model = Paragraph
        fields = ("text", )
        widgets = {"text": forms.Textarea(attrs={"autofocus": "on",}),}

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ("title", )
        widgets = {"title": forms.TextInput(attrs={"autofocus": "on",}),}

hsvpy/stories/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Story, Paragraph
from .forms import ParagraphForm, StoryForm

def index(request):
    stories = Story.objects.all()

    return render(request, 'stories/index.html', locals())

def show_story(request, story_id):
    story = get_object_or_404(Story, pk=int(story_id))

    return render(request, 'stories/story.html', locals())

@login_required
def add_story(request):
    story = Story(created_by=request.user)

    form = StoryForm(request.POST or None, instance=story)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("add-paragraph", kwargs={"story_id": story.id,}))

    return render(request, 'stories/add-story.html', locals())

@login_required
def edit_story(request, story_id):
    story = get_object_or_404(Story, pk=int(story_id))

    form = StoryForm(request.POST or None, instance=story)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("show-story", kwargs={"story_id": story.id,}))

    return render(request, 'stories/edit-story.html', locals())

@login_required
def edit_paragraph(request, story_id, para_id=None):
    story = get_object_or_404(Story, pk=int(story_id))

    if para_id:
        paragraph = get_object_or_404(Paragraph, pk=int(para_id), story=story)
        template = 'stories/edit-paragraph.html'
    else:
        paragraph = Paragraph(story=story, written_by=request.user)
        template = 'stories/add-paragraph.html'

    form = ParagraphForm(request.POST or None, instance=paragraph)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("show-story", kwargs={"story_id": story.id,}))

    return render(request, template, locals())

hsvpy/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}hsvpy{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/hsvpy.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to hsvpy.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">hsvpy</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li class="active"><a href="{% url "stories" %}">Stories</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <h1>{% block page_title %}Example Base Template{% endblock page_title %}</h1>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/hsvpy.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

hsvpy/templates/stories/add-paragraph.html
{% extends "base.html" %}
{% block page_title %}{{ story }}{% endblock page_title %}
{% block content %}

    {% if story.last10paras.count %}
        <h2>You are adding a paragraph after:</h2>
    {% else %}
        <h2>Start this story off on the right foot!</h2>
    {% endif %}

    <ul>
    {% for para in story.last10pararaphs %}
        <li>{{ para }}</li>
    {% endfor %}
    </ul>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add Paragraph" />
    </form>
{% endblock content %}

hsvpy/templates/stories/add-story.html
{% extends "base.html" %}
{% block page_title %}Add a new Story{% endblock page_title %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add Story" />
    </form>
{% endblock content %}

hsvpy/templates/stories/edit-paragraph.html
{% extends "base.html" %}
{% block page_title %}{{ story }}{% endblock page_title %}
{% block content %}
    <h2>Editing the paragraph:</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save Paragraph" />
    </form>
{% endblock content %}

hsvpy/templates/stories/edit-story.html
{% extends "base.html" %}
{% block page_title %}Edit the story title{% endblock page_title %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save Changes" />
    </form>
{% endblock content %}

hsvpy/templates/stories/index.html
{% extends "base.html" %}

{% block page_title %}List of Stories{% endblock page_title %}

{% block content %}
    <ul>
    {% for story in stories %}
        <li><a href="{%url "show-story" story_id=story.id %}">{{ story }}</a></li>
    {% endfor %}
        <li><a href="{%url "add-story" %}">Add your own story</a></li>
    </ul>

{% endblock content %}

hsvpy/templates/stories/story.html
{% extends "base.html" %}
{% block page_title %}{{ story }} <a href="{% url "edit-story" story_id=story.id %}">(edit)</a>{% endblock page_title %}
{% block content %}
    <ul>
    {% for para in story.paragraph_set.all %}
        <li><a href="{% url "edit-paragraph" story_id=story.id para_id=para.id %}">{{ para }}</a></li>
    {% endfor %}
        <li>The end for now....</li>
        <li><a href="{% url "add-paragraph" story_id=story.id %}">Add to this story</a></li>
    </ul>
{% endblock content %}